apiVersion: v1
kind: Service
metadata:
  name: customers-service
  namespace: petclinic-dev
  labels:
    app.kubernetes.io/name: customers-service
    app.kubernetes.io/part-of: petclinic
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: customers-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
