apiVersion: v1
kind: ConfigMap
metadata:
  name: vets-service-config
  namespace: petclinic-dev
  labels:
    app.kubernetes.io/name: vets-service
    app.kubernetes.io/part-of: petclinic
    app.kubernetes.io/managed-by: Helm
data:
  CONFIG_SERVER_URL: "http://config-server:8888"
  SPRING_DATASOURCE_URL: "jdbc:mysql://petclinic-dev-mysql.cfmmsg4kemne.eu-central-1.rds.amazonaws.com:3306/petclinic"
