apiVersion: v1
kind: Service
metadata:
  name: admin-server
  namespace: petclinic-dev
  labels:
    app.kubernetes.io/name: admin-server
    app.kubernetes.io/part-of: petclinic
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: admin
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: admin-server
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      protocol: TCP
