apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "petclinic-service.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "petclinic-service.labels" . | nindent 4 }}
data:
  CONFIG_SERVER_URL: "http://config-server:8888"
  SPRING_APPLICATION_NAME: {{ include "petclinic-service.name" . }}
  {{- if hasKey .Values "configMap" }}
  {{- range $key, $value := .Values.configMap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
