apiVersion: v1
kind: ConfigMap
metadata:
  name: config-server-config
  namespace: petclinic-dev
  labels:
    app.kubernetes.io/name: config-server
    app.kubernetes.io/part-of: petclinic
    app.kubernetes.io/managed-by: Helm
data:
  GIT_REPO: "https://github.com/spring-petclinic/spring-petclinic-microservices-config"
