apiVersion: v1
kind: ServiceAccount
metadata:
  name: config-server
  namespace: petclinic-dev
  labels:
    app.kubernetes.io/name: config-server
    app.kubernetes.io/part-of: petclinic
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: server
