apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway
  namespace: petclinic-dev
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: petclinic
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: gateway
