apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rds-credentials
  namespace: petclinic-dev
  labels:
    app.kubernetes.io/part-of: petclinic
    app.kubernetes.io/managed-by: Helm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: rds-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: petclinic/dev/rds-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: petclinic/dev/rds-credentials
        property: password
