apiVersion: v1
kind: ResourceQuota
metadata:
  name: petclinic-dev-quota
  namespace: petclinic-dev
  labels:
    app.kubernetes.io/part-of: petclinic
    environment: dev
spec:
  hard:
    requests.cpu: "4"
    requests.memory: "4Gi"
    limits.cpu: "4"
    limits.memory: "4Gi"
    pods: "30"
  scopeSelector:
    matchExpressions:
      - operator: In
        scopeName: PriorityClass
        values: ["default"]
